version: "3.8"
# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        IMAGE_BASE: ${IMAGE_BASE:-ghcr.io/ai-dock/python:3.10-cuda-11.8.0-base-22.04}
      tags:
        - "ghcr.io/ai-dock/jupyter-python:${IMAGE_TAG:-3.10-cuda-11.8.0-base-22.04}"
        
    image: ghcr.io/ai-dock/jupyter-python:${IMAGE_TAG:-3.10-cuda-11.8.0-base-22.04}
    
    ## For Nvidia GPU's - You probably want to uncomment this
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
    
    security_opt:
      # For Rclone mount
      - apparmor:unconfined
      # For AMD GPU
      #- seccomp:unconfined
    
    cap_add:
      # For Rclone mount
      - SYS_ADMIN
    
    devices:
      # For Rclone mount
      - "/dev/fuse:/dev/fuse"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"
      #- "/dev/dri:/dev/dri"
      
    # For AMD GPU
    #group_add:
    #  - video
    #  - render
    
    volumes:
      # For Rclone mount
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./config/rclone:/etc/rclone
      # Workspace
      - ./workspace:${WORKSPACE:-/workspace}:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning/default.sh:/opt/ai-dock/bin/provisioning.sh
    
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST:-2222}:${SSH_PORT:-22}
        # Web UI for easy service access
        - ${REDIRECTOR_PORT_HOST:-1111}:1111
        # Jupyter server
        - ${JUPYTER_PORT_HOST:-8888}:8888
        # Rclone webserver for interactive configuration
        - ${RCLONE_PORT_HOST:-53682}:53682
   
    environment:
        # Don't enclose values in quotes
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        - SSH_PORT=${SSH_PORT:-22}
        - WORKSPACE=${WORKSPACE:-/workspace}
        - WORKSPACE_SYNC=${WORKSPACE_SYNC:-true}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-true}
        - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
        - WEB_USER=${WEB_USER:-user}
        - WEB_PASSWORD=${WEB_PASSWORD:-password}
        - SERVERLESS=${SERVERLESS:-false}
        #- PROVISIONING_SCRIPT=https://raw.githubusercontent.com/ai-dock/jupyter-python/main/config/provisioning/default.sh
