version: "3.8"
# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        IMAGE_BASE: ${IMAGE_BASE}
      tags:
        - "ghcr.io/ai-dock/jupyter-python:${IMAGE_TAG}"
        
    image: ghcr.io/ai-dock/jupyter-python:${IMAGE_TAG}
    
    security_opt:
      # For Rclone mount
      - apparmor:unconfined
      # For AMD GPU
      #- seccomp:unconfined
    
    cap_add:
      # For Rclone mount
      - SYS_ADMIN
    
    devices:
      # For Rclone mount
      - "/dev/fuse:/dev/fuse"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"
      #- "/dev/dri:/dev/dri"
      
    # For AMD GPU
    #group_add:
    #  - video
    #  - render
    
    volumes:
      # For Rclone mount
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./config/rclone:/etc/rclone
      # Workspace
      - ./workspace:${WORKSPACE}:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning/default.sh:/opt/ai-dock/bin/provisioning.sh
    
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST}:${SSH_PORT}
        # Jupyter server
        - ${JUPYTER_PORT_HOST}:${JUPYTER_PORT}
        # Rclone webserver for interactive configuration
        - ${RCLONE_PORT_HOST}:53682
   
    environment:
        # Don't enclose values in quotes
        - JUPYTER_PORT=${JUPYTER_PORT}
        - JUPYTER_TOKEN=${JUPYTER_TOKEN}
        # Allows running true SSH alongside provider proxy SSH
        - SSH_PORT=${SSH_PORT}
        - WORKSPACE=${WORKSPACE}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS}
        #- PROVISIONING_SCRIPT=https://raw.githubusercontent.com/ai-dock/jupyter-python/main/config/provisioning/default.sh
